//! ML-KEM-768 keygen — generates a random seed, derives keypair, encapsulates.
//!
//! Run with: cargo run --release
//!
//! Output: src/keys.rs (constants for bare-metal firmware)

#![allow(clippy::unwrap_used, clippy::expect_used)] // host-side tool, not firmware

use ml_kem::kem::{Decapsulate, KeyExport};
use ml_kem::{array::Array, DecapsulationKey, MlKem768};

fn random_bytes(buf: &mut [u8]) {
    // getrandom is already a transitive dependency
    getrandom::getrandom(buf).expect("OsRng failed");
}

fn main() {
    // Real random 64-byte seed from hardware RNG / OS entropy
    let mut seed_bytes = [0u8; 64];
    random_bytes(&mut seed_bytes);
    let seed = Array::try_from(seed_bytes.as_slice()).unwrap();

    // Deterministic key derivation from seed
    let dk = DecapsulationKey::<MlKem768>::from_seed(seed);
    let ek = dk.encapsulation_key();

    // Encapsulate with OS randomness → (ciphertext, shared secret)
    let mut m = [0u8; 32];
    random_bytes(&mut m);
    let m_arr = Array::try_from(m.as_slice()).unwrap();
    let (ct, ss) = ek.encapsulate_deterministic(&m_arr);

    // Print Rust source
    println!("// Auto-generated by keygen — DO NOT EDIT");
    println!("//");
    println!("// ⚠️  Generated from real OS randomness (getrandom).");
    println!("//     Re-run `cargo run --release` in scripts/keygen to rotate.");
    println!("//");
    println!("// ML-KEM-768 keypair + encapsulation for bare-metal firmware.");
    println!();
    print_array("DK", &seed_bytes);
    print_array("EK", ek.to_bytes().as_slice());
    print_array("CT", ct.as_slice());
    print_array("SS", ss.as_slice());

    // Verify round-trip
    let ct_arr = Array::try_from(ct.as_slice()).unwrap();
    let ss2 = dk.decapsulate(&ct_arr);
    assert_eq!(ss.as_slice(), ss2.as_slice(), "decapsulation mismatch!");
    eprintln!("✓ Keygen OK — seed, dk, ek, ct, ss all valid");
}

fn print_array(name: &str, data: &[u8]) {
    println!("pub const {}: [u8; {}] = [", name, data.len());
    for chunk in data.chunks(16) {
        let hex: Vec<String> = chunk.iter().map(|b| format!("0x{:02x}", b)).collect();
        println!("    {},", hex.join(", "));
    }
    println!("];");
    println!();
}
